---
# Source: busybox/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mybusybox2
  labels:
    helm.sh/chart: busybox-0.1.0
    app.kubernetes.io/name: busybox
    app.kubernetes.io/instance: mybusybox2
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
